### ISSUE TITLE
(SystemJS) Module not already loaded loading "../../Observable"

### ISSUE THREAD

**Issue by Alyaeri** [MurhafSousli/ng-gallery#10]
Hiya,

When I attempt to install your library using npm on a copy of the Angular 2 seed, running version 4.1.0-beta.0, I continue to run into this error:

"(SystemJS) Module not already loaded loading "../../Observable" as http://localhost:5555/Observable."

Which stops the app from running. I've followed you start up instructions closely, and when I remove GalleryModule from app.module, the app runs perfectly.

What am I missing?

Thanks!

**Comment by MurhafSousli** [comment]
Hi @Alyaeri,
It is fixed now, update to **v0.6.3**, here is a working [plnkr](https://plnkr.co/edit/ab3EKfuvfKBppl7T8kFL?p=preview)

**Comment by Alyaeri** [comment]
@MurhafSousli It's working perfectly now, thanks so much!

**Comment by MurhafSousli** [comment]
You are welcome!
