### ISSUE TITLE
gallery-main (bounding box) does not respect height

### ISSUE THREAD

**Issue by kryptonianson** [MurhafSousli/ng-gallery#19]
In the file "ng-gallery/src/component/gallery/gallery.component.scss" the style defines a height of 500px. This is fine as a default, however when I am placing the gallery as a tool I am unable to override the size of "gallery-main" in my css. Three possible solutions:

1. Simply remove the height from the style so that it will inherit whatever the parent is. (I favor this.)
2. Make it so that the bounding container respects the image size specified.
3. Provide bounding size properties.

This is a huge issue for me at the me at the moment, and I will not be able to use the project, and I really like it. Please advise :) And thank you for a great product.

**Comment by MurhafSousli** [comment]
Hi @kryptonianson, Welcome!

> 1. Simply remove the height from the style so that it will inherit whatever the parent is. (I favor this.)

This height is just a default value for the wrapper height. (it is not necessary, I will remove it in a future update 👍).

For now, you are probably trying to override it from your component style, which will not work!
Override the height from the global style `style.css`
```css
your-component-name gallery gallery-main {
    height: auto;
}
```
> 3. Provide bounding size properties.

If you look inside [Basic Demo](https://murhafsousli.github.io/ng-gallery/#/basic) you can adjust the height from the config.

![image](https://user-images.githubusercontent.com/8130692/27143080-c5319af4-5135-11e7-819f-ac44ed937424.png)

As you see in the screenshot, I have disabled the default ~~`height: 500px`~~ and set `450px` in config.

> 2. Make it so that the bounding container respects the image size specified.

If so, the gallery size will be changing every time the image changes (resulting in bad UX), putting in mind that you have navigation, thumbs, bullets on top on it (imagine an image with `500x80` size) ! the container size must be set.

**Comment by kryptonianson** [comment]
I tried what you have suggested and no matter what combination I put in the global styles it will not override what is in the resulting "gallery-main[_ngcontent-c2]" style. I have no issues setting the gallery height in general. That works great. It is simply the bounding "gallery-main[_ngcontent-c2]" box. If you have further suggestions as to what I can do in my global style I am happy to do it.

**Comment by kryptonianson** [comment]
On a side note, do you have an ETA on the next release which will include removing the default height in gallery.component.scss?

**Comment by MurhafSousli** [comment]
@kryptonianson use `height: auto !important;` in the style.

I don't really know when I will be pushing another update, I was hoping to find contributors to help improve this project. however, I will add improvement on my free time.

**Comment by kryptonianson** [comment]
I am sorry, for sure I don't know what I was thinking. !important of course is the problem. Thank you for your patience. But the way I really love this component. Great work.

**Comment by kefengwei** [comment]
hello, is there update the 'gallery-main'? i didn't find this class.I try to just add to gallery,but there only show the thumbs.so how can i respect the height  now?
