### ISSUE TITLE
gallery opens on top

### ISSUE THREAD

**Issue by superstarmcawesome** [MurhafSousli/ng-gallery#20]
Hey there, 

I have multiple gallerys and depending on the folder you click you see some images and the gallery gets injected with some images. The problem is the modal always opens on top of the page. So if I scroll down and open a gallery it always looks like nothing happened. I always need to scroll up to see the modal with the images.

Any ideas on this one?

**Comment by MurhafSousli** [comment]
Hi @superstarmcawesome, add your full usage

**Comment by MurhafSousli** [comment]
@superstarmcawesome Hi, sorry for late response. this is fixed now. the new update uses angular cdk for the overlay
