### ISSUE TITLE
Warning: Can't resolve all parameters for GalleryService in `gallery.service.d.ts: (?)`. This will become an error in Angular v5.x

### ISSUE THREAD

**Issue by leocaseiro** [MurhafSousli/ng-gallery#21]
> Warning: Can't resolve all parameters for GalleryService in `/node_modules/ng-gallery/service/gallery.service.d.ts: (?)`. This will become an error in Angular v5.x

Hi, if you run AOT or build -prod, you'll see this warning on `@angular@4.2.4`.

I couldn't find myself what is not resolved, but I thought openning this issue will get some more help. Thanks

**Comment by MurhafSousli** [comment]
I am getting this issue on different plugins, most probably it is caused by ngc I used for building the module

**Comment by ekiras** [comment]
any update on this one, i am also getting same warning on one of of my library

**Comment by MurhafSousli** [comment]
@ekiras This will be fixed in the next update

**Comment by kondi** [comment]
@MurhafSousli Could we have a release soon? Angular 5 has released rc0 and I would like to prepare my app for the final version.

**Comment by MurhafSousli** [comment]
This is fixed now

**Comment by mfrro** [comment]
@MurhafSousli 
The fix doesn't seem to be in the current release (1.0.0-beta.8), are you planning on releasing soon? Thanks
