### ISSUE TITLE
Loaded but hidden modal gallery pops-up when keypressed

### ISSUE THREAD

**Issue by Fluuub** [MurhafSousli/ng-gallery#24]
Hey there ;)

Great & easy component, but I would expect to be able to load the modal component, fill it with images and then only wait for my command to display it (Ex: gallery.set(x)), but keyboardInput is triggered when component is first loaded but not visible, hence popping up untimely with keys 37, 39, 13 & 27...

Any mean to disable this at component load?

Thanks

**Comment by MurhafSousli** [comment]
Hey @Fluuub, this is fixed now
