### ISSUE TITLE
using ng-gallery generally for content not only for images

### ISSUE THREAD

**Issue by maku** [MurhafSousli/ng-gallery#25]
Currently ng-gallery is only usable for images (at least as far as I understand)

But it would be very useful when it could be used for more than just images (videos, ordinary content etc.)

Do you plan such a feature??

TIA

**Comment by MurhafSousli** [comment]
Hi @maku, you are right, It is only for images. I have a plan to update in the future, but currently I overloaded with work.

I am wondering what to display for thumbnails in case of video or template?

**Comment by maku** [comment]
@MurhafSousli in this case, per default a thumbnail is not that important. Maybe a thumnail can optionally be defined as additional image resource...

**Comment by MurhafSousli** [comment]
I think this is possible using the `item.text`
```ts
 items: GalleryItem[] = [
  // ... ,
  {
    src: '...';
    thumbnail: '...';
    text: `
       <h3> HTML CONTENT HERE </h3>
    `
  }
];
```
Add custom class to your content wrapper using the config
```ts
config: GalleryConfig = {
  // ... ,
  description: {
      className: 'contentClass'
  }
}
```

**Comment by maku** [comment]
@MurhafSousli Sorry, I don't get it what I can achieve with this. I don't have a source. So the source area is empty... (only the loading image is presented).
e.g. I would like to show a video (in the area where the src image is presented).

**Comment by MurhafSousli** [comment]
@maku Currently it is not possible to replace the image, but there is an issue for the video https://github.com/MurhafSousli/ng-gallery/issues/22
