### ISSUE TITLE
Doesn't work with Server Side Rendering

### ISSUE THREAD

**Issue by mfrro** [MurhafSousli/ng-gallery#32]
Hi,
I'm currently trying to get my angular project to work with SSR. One of the modules that causes errors when used on the server is ng-gallery. I get several "Unexpected token export" and "Unexpected token import" errors. There is an issue regarding this problem at angular/angular-cli#7200. The verdict seems to be, that the modules causing the error have to be changed to conform to the angular package format. I'm not sure what that would mean for this package. The issue should be fixable in the build process, as it seems to be an issue of targeting commonjs.

**Comment by MurhafSousli** [comment]
Hi @mfrro, this should be fixed in the next update
