### ISSUE TITLE
Time for fork or new maintainers?

### ISSUE THREAD

**Issue by kondi** [MurhafSousli/ng-gallery#34]
Hi!

It looks like this project is quite abandoned now :( The current release version is not supported by Angular 5 and there is no update about it from the project owner, see https://github.com/MurhafSousli/ng-gallery/issues/21#issuecomment-333092452.
I can see forks with lot of new commits:
- https://github.com/Kuchasz/ps-photo-gallery
- https://github.com/slavik990/ng-gallery
- https://github.com/kuwas/ngx.gallery.ts

Guys, don't you want to join forces somehow? I am pretty sure these things could be useful for other ng-gallery users as well. I would be happy to see a new release :)

**Comment by kuwas** [comment]
@kondi
If anything I would just create a new library, I'm not fond of some of the behaviors in this one.

**Comment by MurhafSousli** [comment]
@kondi The project is not abandoned. in fact I am working on an update, but I can't give you dates! I am overloaded with work, plus this is not the only plugin I am working on at the moment!
