### ISSUE TITLE
Not an issue, is most like a feature request

### ISSUE THREAD

**Issue by Luis16287** [MurhafSousli/ng-gallery#35]
_**Is it possible to add features like zoom in and out an image, rotate it, mirror effect? It would be great. It's a great work, thank you very much.**_

**Comment by MurhafSousli** [comment]
@Luis16287 This is nice to have, but I don't think we will have this in the next update, currently we want to fix some bugs and add some enhancements, I will keep this open for future updates

**Comment by Luis16287** [comment]
Sorry to hear that, thanks again for your work. I hope to see the next updates. Regards

**Comment by khanhvuNOIS** [comment]
+1

**Comment by MurhafSousli** [comment]
Can you collaborate on this?

**Comment by MurhafSousli** [comment]
Doesn't seem to be happening
