### ISSUE TITLE
gallery overlay close button is clicking behind & loader missing

### ISSUE THREAD

**Issue by deokey** [MurhafSousli/ng-gallery#41]
### Bug Report or Feature Request
```
- [X] bug report
- [X] feature request
```

### OS and Version?

> macOS Sierra 

### Versions
Angular CLI: 1.5.0
Node: 8.7.0
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cdk: 5.0.0-rc.1
angular/cli: 1.5.0
angular/flex-layout: 2.0.0-beta.10-4905443
angular/material: 5.0.0-rc0
angular-devkit/build-optimizer: 0.0.33
angular-devkit/core: 0.0.21
angular-devkit/schematics: 0.0.37
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

### Repro steps

Close button  issue:
just click on the close button from the gallery overlay and if you have some link, button with an action, even the gallery itself behind the close button it triggers automatically, the only fix that i could find without changing the source code was in my .css changed the position absolute atribute for position fixed, then the problem stops. 

Loader missing issue:
the loader is missing, i dont know which kind of file is.. img,svg,gif so i cant fix the console error saying that "loader", in this case oval is not found.
![captura de pantalla 2017-11-28 a la s 6 49 00 p m](https://user-images.githubusercontent.com/18384611/33348443-d7bff76e-d46c-11e7-8e6f-7619fb6aa6f6.png)

Please tell me where i can find the loader, Thanks!

**Comment by MurhafSousli** [comment]
Hi @deokey, After beta.8 the loader icon should take the full path of the icon, the doc is not updated yet

For the loader, try
```
loader: {
    icon: "{PATH_TO_ICON}"
},
```
You can also use an inline data to avoid the icon request. the document will be updated as soon as I fix the build setup problem
