### ISSUE TITLE
Double click on Thumbnails  Bug

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ng-gallery#45]
when Double click on Thumbnails on https://murhafsousli.github.io/ng-gallery/#/basic
we have result:
![screenbug](https://user-images.githubusercontent.com/28723724/34049413-62ee13b2-e1c8-11e7-8a2e-826ba19768a4.png)

how fix it?

**Comment by MurhafSousli** [comment]
@CosmoFruit fixed in v1.0.1
