### ISSUE TITLE
(SystemJS) expected expression, got '<' error

### ISSUE THREAD

**Issue by Yauheni-Butski** [MurhafSousli/ng-gallery#46]
Step 1 in "Installation" chapter throw for me error. Application can't start on initial page. Added all that described in app.module.ts. 
Without (or if just comment) all for 'BrowserAnimationsModule ' and 'GalleryModule' - application starts fine.

This is the screenshot with error in console:
https://www.screencast.com/t/JDRxjEuFfno

Any suggestions? 

UPD. The error was even with only 'BrowserAnimationsModule'. Updated my 'systemjs.config.js', added:
`
      '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
      '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
`
And application have started work. After that tried uncomment all for 'GalleryModule' and got the same error again. Any other dependencies that should be added?

**Comment by MurhafSousli** [comment]
Hi @Yauheni-Butski
```ts
'@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
'@angular/cdk/bidi': 'npm:@angular/cdk/bundles/cdk-bidi.umd.js',
'@angular/cdk/coercion': 'npm:@angular/cdk/bundles/cdk-coercion.umd.js',
'@angular/cdk/keycodes': 'npm:@angular/cdk/bundles/cdk-keycodes.umd.js',
'@angular/cdk/platform': 'npm:@angular/cdk/bundles/cdk-platform.umd.js',
'@angular/cdk/portal': 'npm:@angular/cdk/bundles/cdk-portal.umd.js',
'@angular/cdk/overlay': 'npm:@angular/cdk/bundles/cdk-overlay.umd.js',
'@angular/cdk/scrolling': 'npm:@angular/cdk/bundles/cdk-scrolling.umd.js',
'ng-gallery': 'npm:ng-gallery/bundles/ng-gallery.umd.js',
```
Here is a working [plunkr](https://plnkr.co/edit/D2bR0SQ5eI63e5BLbIrz?p=preview)
