### ISSUE TITLE
Gallery has a prev control and a next control for one image.

### ISSUE THREAD

**Issue by evasiliskin** [MurhafSousli/ng-gallery#48]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by evasiliskin** [comment]
If gallery has only one image I see navigation controls.

**Comment by MurhafSousli** [comment]
@evasiliskin I just checked it with this [stackblitz](https://stackblitz.com/edit/ng-gallery-zqv68f?file=app/app.component.html), the navigation does not appear for one image

**Comment by maku** [comment]
@MurhafSousli here is an stackblitz example which shows that this does not work!
https://angular-buzb5v.stackblitz.io (https://stackblitz.com/edit/angular-buzb5v)
