### ISSUE TITLE
`src-full` doesn't work in Angular View Template

### ISSUE THREAD

**Issue by johannhuang** [MurhafSousli/ng-gallery#49]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS Sierra

### Versions

```
@angular/cli: 1.3.0
node: 8.4.0
os: darwin x64
@angular/animations: 4.4.6
@angular/cdk: 5.0.2
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.3.0

@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps

When `src-full` being added to `<img>` tag, bug appears.

### The log given by the failure

```
Can't bind to 'src-full' since it isn't a known property of 'img'. ("class="photo" *ngFor="let photo of photos">
      <figure>
        <img src="{{ photo.thumbnail }}" [ERROR ->]src-full="{{ photo.original }}" alt="" title="" />
        <figcaption></figcaption>
      </figure>
```

### Desired functionality

No idea.

### Mention any other details that might be useful

By the way, can you make responsive implementation of lightbox? And is there any documentation about `GalleryConfig`?

Thanks!!

**Comment by johannhuang** [comment]
### Desired functionality

Is it possible to add `full-src` directive?

## Solution
Finally, I chose `this.gallery.load(this.images);` with `(click)="gallery.open(i)"` method.

## More
By the way, can you make responsive implementation of lightbox? And is there any documentation about `GalleryConfig`?

**Comment by johannhuang** [comment]
I fixed my Responsive Lightbox need via following code block in `styles.scss`

```
/* ng-gallery style fix */
.g-overlay {
  width: 80%;
}
```

**Comment by MurhafSousli** [comment]
@johannhuang Did you try `[attr.src-full]` ?

**Comment by johannhuang** [comment]
@MurhafSousli Thanks for you answer. I think the problem is that Angular provides quite strict rules for html. If the html is not provided by api, it is not good practice to use `src-full`. And I guess it is time to close this issue.
