### ISSUE TITLE
Animation for modal gallery

### ISSUE THREAD

**Issue by Insomniax** [MurhafSousli/ng-gallery#8]
Hi there, the feature is awesome in general. I used the modal version of the gallery https://murhafsousli.github.io/ng-gallery/#/modal but it actually opens with a `popup` animation. Is it possible to change the animation effect of the modal? I want it to `slide down` for example.

**Comment by MurhafSousli** [comment]
Hi @Insomniax, I definitely have a plan to support custom animation, but angular animation is still not dynamic yet, so currently it is not possible for users to use their own animation, unless the animation is already added (which increases the package size). we need to wait for dynamic animation to be possible. Or  we can replace the animation with a class where users are able to define their own animation (same way animate.css works).
